### ISSUE TITLE
New Referral Message Fails to Send

### ISSUE THREAD

**Issue by codelion7** [codelion7/affiliatewp-buddypress-integration#3]
All of the data necessary to send the bp message is present according to the debug output. Need to check error log for further info.

**Comment by codelion7** [comment]
Found cause: BadgeOS Community Add-on #5 

Once deactivated, the new referral message works.

**Comment by MiggyS** [comment]
Was there ever any solution found for this? I have a plugin that uses private messaging in buddypress to send alerts that also has the same issue and only works again properly once this plugin is disabled.

I know it's not relevant to affiliatewp but you guys seem to be the only other place I've seen the issue posted.

**Comment by codelion7** [comment]
Unfortunately, no. The only solution thus far, is to deactivate the BadgeOS Community add-on. Honestly, BadgeOS and quite a few of its add-ons have conflicts with other plugins as well. I had to stop using it altogether.
